### ISSUE TITLE
TypeError: no implicit conversion of nil into String (TypeError)

### ISSUE THREAD

**Issue by Faq** [javier-menendez/sprockets_terser_with_source_maps#12]
With Rails 7.1.4.2, Ruby 3.3.5, running 
`RAILS_ENV=production bundle exec rake assets:precompile --trace`

```
TypeError: no implicit conversion of nil into String (TypeError)

      filename = File.join(Rails.application.config.assets.prefix, prefix, "#{name}-#{digest(data)}.#{extension}")
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/sprockets_terser_with_source_maps-2.1.0/lib/sprockets_terser_with_source_maps/compressor.rb:56:in `join'
/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/sprockets_terser_with_source_maps-2.1.0/lib/sprockets_terser_with_source_maps/compressor.rb:56:in `generate_asset_file'
/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/sprockets_terser_with_source_maps-2.1.0/lib/sprockets_terser_with_source_maps/compressor.rb:33:in `call'
/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/terser-1.2.4/lib/terser/compressor.rb:23:in `call'
/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/sprockets-4.2.1/lib/sprockets/processor_utils.rb:84:in `call_processor'
/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/sprockets-4.2.1/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/sprockets-4.2.1/lib/sprockets/processor_utils.rb:65:in `reverse_each'
/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/sprockets-4.2.1/lib/sprockets/processor_utils.rb:65:in `call_processors'
/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/sprockets-4.2.1/lib/sprockets/loader.rb:184:in `load_from_unloaded'
/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/sprockets-4.2.1/lib/sprockets/loader.rb:59:in `block in load'
/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/sprockets-4.2.1/lib/sprockets/loader.rb:339:in `fetch_asset_from_dependency_cache'
/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/sprockets-4.2.1/lib/sprockets/loader.rb:43:in `load'
/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/sprockets-4.2.1/lib/sprockets/cached_environment.rb:44:in `block in load'
/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/map.rb:207:in `block in fetch_or_store'
/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/map.rb:187:in `fetch'
/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/map.rb:206:in `fetch_or_store'
/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/sprockets-4.2.1/lib/sprockets/cached_environment.rb:44:in `load'
/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/sprockets-4.2.1/lib/sprockets/bundle.rb:32:in `block in call'
/.rbenv/versions/3.3.5/lib/ruby/3.3.0/set.rb:501:in `each_key'
/.rbenv/versions/3.3.5/lib/ruby/3.3.0/set.rb:501:in `each'
/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/sprockets-4.2.1/lib/sprockets/bundle.rb:31:in `call'
/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/sprockets-4.2.1/lib/sprockets/processor_utils.rb:84:in `call_processor'
/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/sprockets-4.2.1/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/sprockets-4.2.1/lib/sprockets/processor_utils.rb:65:in `reverse_each'
/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/sprockets-4.2.1/lib/sprockets/processor_utils.rb:65:in `call_processors'
/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/sprockets-4.2.1/lib/sprockets/loader.rb:184:in `load_from_unloaded'
/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/sprockets-4.2.1/lib/sprockets/loader.rb:59:in `block in load'
/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/sprockets-4.2.1/lib/sprockets/loader.rb:339:in `fetch_asset_from_dependency_cache'
/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/sprockets-4.2.1/lib/sprockets/loader.rb:43:in `load'
/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/sprockets-4.2.1/lib/sprockets/cached_environment.rb:44:in `block in load'
/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/map.rb:207:in `block in fetch_or_store'
/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/map.rb:187:in `fetch'
/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/map.rb:206:in `fetch_or_store'
/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/sprockets-4.2.1/lib/sprockets/cached_environment.rb:44:in `load'
/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/sprockets-4.2.1/lib/sprockets/base.rb:81:in `find_asset'
/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/sprockets-4.2.1/lib/sprockets/base.rb:88:in `find_all_linked_assets'
/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/sprockets-4.2.1/lib/sprockets/manifest.rb:125:in `each'
/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/sprockets-4.2.1/lib/sprockets/manifest.rb:125:in `to_a'
/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/sprockets-4.2.1/lib/sprockets/manifest.rb:125:in `block (2 levels) in find'
/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `block in synchronize'
/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `synchronize'
/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `synchronize'
/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:22:in `execute'
/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/promise.rb:564:in `block in realize'
/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:359:in `run_task'
/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:350:in `block (3 levels) in create_worker'
<internal:kernel>:187:in `loop'
/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:341:in `block (2 levels) in create_worker'
/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `catch'
/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/concurrent-ruby-1.3.4/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:340:in `block in create_worker'
Tasks: TOP => assets:precompile
```

**Comment by javier-menendez** [comment]
Could you provide the settings that you are using? seems like some of the `prefix` values are `nil`. I can't reproduce the problem with the default values

**Comment by Faq** [comment]
and on top require "terser_with_source_maps"
No settings, just config.assets.js_compressor = :terser_with_source_maps

**Comment by javier-menendez** [comment]
@Faq with rails you don't need the require, and the correct require should be:

`require "sprockets_terser_with_source_maps"`

With new rails 7.1.4.2 generated app I can't reproduce it, can you provide some sample code, and the asset on which is failing?

**Comment by Faq** [comment]
Sorry, as this did not worked out, in `production.rb` went with terser:
```
Sprockets.register_compressor("application/javascript", :terser, Terser::Compressor)
config.assets.js_compressor = :terser
```
